---
type: yml

env_file:
    - .env


httpServer:
  port: 7660

postgres:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "postgres_telbot"
  database: "telegram_service_platform"
  sslmode: "disable"

telegram:
  token: ${TELEGRAM_BOT_TOKEN}
  debug: false

redis:
  host: localhost
  port: 6380
  password: MyStrongPassword
  db: 0

productService:
  PriceCacheTTL: "60m"

fzr:
  base_url: "https://api.fzr.cards/api/v2"
  api_key: "fc_1c000a69d23825314267b0d9"
  timeout: "10s"

exchangeRate:
  ton_usd_url: "https://api.coingecko.com/api/v3/simple/price?ids=the-open-network&vs_currencies=usd"
  usd_irr_url: "https://api.wallex.ir/v1/otc/markets"
  timeout: "10s"

priceService:
  stars_price_ttl: "2h"
  premium_price_ttl: "2h"
  currency_ttl: "2h"

scheduler:
  currency_refresh_interval: "1h"
  stars_refresh_interval: "1h"
  premium_refresh_interval: "1h"
  payment_verify_interval: "1m"
  status_sync_interval: "5m"
  payment_expiry_interval: "2m"
  queue_consumer_interval: "1s"

wallet:
  idempotency_processing_ttl: "5m"
  idempotency_completed_ttl: "24h"

smmProviderSvc:
  failure-threshold: 5
  success-threshold: 3
  circuit-timeout: "30s"

checkoutSvc:
  PrefixIdempotencyKey: "DirectIdempotency"
  prefix_wallet_idempotency_key: "WalletIdempotency"
  prefix_Manual_idempotency_key: "ManualIdempotency"

notificationSvc:
  queue_key: "queue:notifications:pending"
paymentVerify:
  queue_key: "queue:orders:paid"

orderFulFiller:
  queue_key: "queue:orders:paid"
  timeout:  "5s"

notificationJob:
  queue_key: "queue:notifications:pending"
  timeout:  "5s"
  PendingLimit: 10
