---
type: yml

httpServer:
  port: 7660

postgres:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "postgres_telbot"
  database: "telegram_service_platform"
  sslmode: "disable"

telegram:
  token: "8873841525:AAGdvvgTW1hAzVjONNZ5apyXGmhEDVKbtZM"
  debug: false

redis:
  host: localhost
  port: 6380
  password: MyStrongPassword
  db: 0

productService:
  PriceCacheTTL: "60m"

fzr:
  base_url: "https://api.fzr.cards/api/v2"
  api_key: "fc_1c000a69d23825314267b0d9"
  timeout: "10s"

exchangeRate:
  ton_usd_url: "https://api.coingecko.com/api/v3/simple/price?ids=the-open-network&vs_currencies=usd"
  usd_irr_url: "https://api.wallex.ir/v1/otc/markets"
  timeout: "10s"

priceService:
  stars_price_ttl: "2h"
  premium_price_ttl: "2h"
  currency_ttl: "2h"

scheduler:
  currency_refresh_interval: "1h"
  stars_refresh_interval: "1h"
  premium_refresh_interval: "1h"