package msgerror

const (
	InternalServerError          = "something went wrong"
	UserNotFound                 = "user not found"
	PaymentNotFound              = "payment not found"
	WalletNotFound               = "wallet not found"
	IdempotencyAlreadyProcessing = "idempotency already processing"
	UserAlreadyExists            = "user already exists"
	InvalidInput                 = "invalid input"
	Unauthorized                 = "unauthorized"
	Forbidden                    = "access forbidden"
	ProductNotFound              = "productkeyboard not found"
	OrderNotFound                = "order not found"
	
	OrderAlreadyPaid        = "order already paid"
	PaymentFailed           = "payment failed"
	PaymentAlreadyProcessed = "payment already processed"
	TelegramOperationFailed = "telegram operation failed"
	Unexpected              = "unexpected"
	TelegramIdInvalid       = "telegram id invalid"
	CacheReadFailed         = "failed to read cache"
	CacheWriteFailed        = "failed to write cache"
	CacheParseFailed        = "failed to parse cache value"
	QueryFailed             = "failed to query"
	QueryScanFailed         = "failed to query scan"
	ExternalServiceFailed   = "external service failed"
	PremiumPriceNotFound    = "premium price not found"
	InvalidPrice            = "invalid price"
	CacheNotFound           = "cache not found"
	MarshalFailed           = "marshal failed"
	UnmarshalFailed         = "unmarshal failed"
	ProviderCreateFailed    = "provider create failed"
)
